/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import javax.swing.JOptionPane;

/**
 *
 * @author MauHernandez
 */
public class NewJFrame extends javax.swing.JFrame {
int contador  = 0;
String lblcont;
int contdoble = 0;
int contadortriple = 0;
int a=1,b=1,c=1,d=1,e=1,f=1,g=1,h=1;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        a1 = new javax.swing.JRadioButton();
        a2 = new javax.swing.JRadioButton();
        a3 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        b1 = new javax.swing.JRadioButton();
        b2 = new javax.swing.JRadioButton();
        b3 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        d3 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        c1 = new javax.swing.JRadioButton();
        c2 = new javax.swing.JRadioButton();
        c3 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        d1 = new javax.swing.JRadioButton();
        d2 = new javax.swing.JRadioButton();
        h3 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        g1 = new javax.swing.JRadioButton();
        f2 = new javax.swing.JRadioButton();
        g2 = new javax.swing.JRadioButton();
        f3 = new javax.swing.JRadioButton();
        g3 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        h1 = new javax.swing.JRadioButton();
        h2 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        e1 = new javax.swing.JRadioButton();
        e2 = new javax.swing.JRadioButton();
        e3 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        f1 = new javax.swing.JRadioButton();
        dobles = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        numq = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        costo = new javax.swing.JLabel();
        al = new javax.swing.JLabel();
        bl = new javax.swing.JLabel();
        cl = new javax.swing.JLabel();
        dl = new javax.swing.JLabel();
        el = new javax.swing.JLabel();
        fl = new javax.swing.JLabel();
        gl = new javax.swing.JLabel();
        hl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(430, 430));

        jLabel1.setText("Puto el que lo lea");

        jLabel2.setText("jLabel2");

        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });

        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });

        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ActionPerformed(evt);
            }
        });

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel2");

        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        jLabel5.setText("jLabel3");

        d3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d3ActionPerformed(evt);
            }
        });

        jLabel6.setText("jLabel3");

        jLabel7.setText("jLabel2");

        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });

        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });

        jLabel8.setText("jLabel3");

        jLabel9.setText("jLabel2");

        d1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d1ActionPerformed(evt);
            }
        });

        d2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d2ActionPerformed(evt);
            }
        });

        h3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h3ActionPerformed(evt);
            }
        });

        jLabel10.setText("jLabel3");

        jLabel11.setText("jLabel2");

        g1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g1ActionPerformed(evt);
            }
        });

        f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f2ActionPerformed(evt);
            }
        });

        g2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g2ActionPerformed(evt);
            }
        });

        f3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f3ActionPerformed(evt);
            }
        });

        g3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g3ActionPerformed(evt);
            }
        });

        jLabel12.setText("jLabel3");

        jLabel13.setText("jLabel3");

        jLabel14.setText("jLabel2");

        h1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h1ActionPerformed(evt);
            }
        });

        h2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h2ActionPerformed(evt);
            }
        });

        jLabel15.setText("jLabel2");

        e1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e1ActionPerformed(evt);
            }
        });

        e2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e2ActionPerformed(evt);
            }
        });

        e3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e3ActionPerformed(evt);
            }
        });

        jLabel16.setText("jLabel3");

        jLabel17.setText("jLabel2");

        f1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f1ActionPerformed(evt);
            }
        });

        dobles.setText("Dobles y triples");
        dobles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doblesActionPerformed(evt);
            }
        });

        jLabel18.setText("Quinielas:");

        numq.setText("1");

        jLabel20.setText("Costo: $");

        costo.setText("25");

        al.setText("_____");

        bl.setText("_____");

        cl.setText("_____");

        dl.setText("_____");

        el.setText("_____");

        fl.setText("_____");

        gl.setText("_____");

        hl.setText("_____");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)
                                        .addGap(35, 35, 35)
                                        .addComponent(b2)
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(b3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(a1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2)
                                        .addGap(35, 35, 35)
                                        .addComponent(a2)
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(d1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9)
                                        .addGap(35, 35, 35)
                                        .addComponent(d2)
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(d3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(c1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)
                                        .addGap(35, 35, 35)
                                        .addComponent(c2)
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(c3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(f1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel17)
                                        .addGap(35, 35, 35)
                                        .addComponent(f2)
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(f3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(e1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel15)
                                        .addGap(35, 35, 35)
                                        .addComponent(e2)
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(e3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(h1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel14)
                                        .addGap(35, 35, 35)
                                        .addComponent(h2)
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(h3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(g1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11)
                                        .addGap(35, 35, 35)
                                        .addComponent(g2)
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(g3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addComponent(jLabel1))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dobles))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(costo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(numq, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(al, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(el, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(hl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(a1)
                    .addComponent(a2)
                    .addComponent(jLabel3)
                    .addComponent(a3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(b1)
                    .addComponent(b2)
                    .addComponent(jLabel5)
                    .addComponent(b3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(c1)
                    .addComponent(c2)
                    .addComponent(jLabel8)
                    .addComponent(c3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(d1)
                    .addComponent(d2)
                    .addComponent(jLabel6)
                    .addComponent(d3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(e1)
                    .addComponent(e2)
                    .addComponent(jLabel16)
                    .addComponent(e3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(f1)
                    .addComponent(f2)
                    .addComponent(jLabel12)
                    .addComponent(f3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(g1)
                    .addComponent(g2)
                    .addComponent(jLabel13)
                    .addComponent(g3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(h1)
                    .addComponent(h2)
                    .addComponent(jLabel10)
                    .addComponent(h3))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(el, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(al, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobles)
                    .addComponent(jButton1))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(costo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(numq, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        // TODO add your handling code here:
        
        if(dobles.isSelected()){
         if(a1.isSelected()&& a2.isSelected()){
             al.setText("LE");
             
         }
         if (a1.isSelected()&& a3.isSelected()){
             al.setText("LV");
             
         }
         if(a2.isSelected() && a3.isSelected()){
             al.setText("EV");
             
         }
         if (a2.isSelected() && a3.isSelected()&&a1.isSelected()){
             al.setText("LEV");
             
         }
        if(!a3.isSelected() && !a2.isSelected() && a1.isSelected()){
            al.setText("L");
                     
        }
        if(!a1.isSelected() && !a2.isSelected() && a3.isSelected()){
            al.setText("V");
            
            
        }
        if(!a1.isSelected() && !a3.isSelected() && a2.isSelected()){
            al.setText("E");
             
        }
        if(!a3.isSelected() && !a2.isSelected() && !a1.isSelected()){
            al.setText("_____");
            
        }
        
        }
        
        else{
            
            a2.setSelected(false);
            a3.setSelected(false);
            al.setText("L");
            
        } 
        
        
        
        
    }//GEN-LAST:event_a1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        if(dobles.isSelected()){
         if(b1.isSelected()&& b2.isSelected()){
             bl.setText("LE");
         }
         if (b1.isSelected()&& b3.isSelected()){
             bl.setText("LV");
         }
         if(b2.isSelected() && b3.isSelected()){
             bl.setText("EV");
         }
         if (b2.isSelected() && b3.isSelected()&&b1.isSelected()){
             bl.setText("LEV");
         }
        if(!b3.isSelected() && !b2.isSelected() && b1.isSelected()){
            bl.setText("L");
        }
        if(!b1.isSelected() && !b2.isSelected() && b3.isSelected()){
            bl.setText("V");
        }
        if(!b1.isSelected() && !b3.isSelected() && b2.isSelected()){
            bl.setText("E");
        }
        if(!b3.isSelected() && !b2.isSelected() && !b1.isSelected()){
            bl.setText("_____");
        }
        
        }
        else{
            b2.setSelected(false);
            b3.setSelected(false);
            bl.setText("L");
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
       if(dobles.isSelected()){
         if(c1.isSelected()&& c2.isSelected()){
             cl.setText("LE");
         }
         if (c1.isSelected()&& c3.isSelected()){
             cl.setText("LV");
         }
         if(c2.isSelected() && c3.isSelected()){
             cl.setText("EV");
         }
         if (c2.isSelected() && c3.isSelected()&& c1.isSelected()){
             cl.setText("LEV");
         }
        if(!c3.isSelected() && !c2.isSelected() && c1.isSelected()){
            cl.setText("L");
        }
        if(!c1.isSelected() && !c2.isSelected() && c3.isSelected()){
            cl.setText("V");
        }
        if(!c1.isSelected() && !c3.isSelected() && c2.isSelected()){
            cl.setText("E");
        }
        if(!c3.isSelected() && !c2.isSelected() && !c1.isSelected()){
            cl.setText("_____");
        }
        
        }
        else{
            c2.setSelected(false);
            c3.setSelected(false);
            cl.setText("L");
        }
    }//GEN-LAST:event_c1ActionPerformed

    private void d1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d1ActionPerformed
        if(dobles.isSelected()){
         if(d1.isSelected()&& d2.isSelected()){
             dl.setText("LE");
         }
         if (d1.isSelected()&& d3.isSelected()){
             dl.setText("LV");
         }
         if(d2.isSelected() && d3.isSelected()){
             dl.setText("EV");
         }
         if (d2.isSelected() && d3.isSelected()&& d1.isSelected()){
             dl.setText("LEV");
         }
        if(!d3.isSelected() && !d2.isSelected() && d1.isSelected()){
            dl.setText("L");
        }
        if(!d1.isSelected() && !d2.isSelected() && d3.isSelected()){
            dl.setText("V");
        }
        if(!d1.isSelected() && !d3.isSelected() && d2.isSelected()){
            dl.setText("E");
        }
        if(!d3.isSelected() && !d2.isSelected() && !d1.isSelected()){
            dl.setText("_____");
        }
        
        }
        else{
            d2.setSelected(false);
            d3.setSelected(false);
            dl.setText("L");
        }
    }//GEN-LAST:event_d1ActionPerformed

    private void g1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g1ActionPerformed
        // TODO add your handling code here:
         if(dobles.isSelected()){
         if(g1.isSelected()&& g2.isSelected()){
             gl.setText("LE");
         }
         if (g1.isSelected()&& g3.isSelected()){
             gl.setText("LV");
         }
         if(g2.isSelected() && g3.isSelected()){
             gl.setText("EV");
         }
         if (g2.isSelected() && g3.isSelected()&& g1.isSelected()){
             gl.setText("LEV");
         }
        if(!g3.isSelected() && !g2.isSelected() && g1.isSelected()){
            gl.setText("L");
        }
        if(!g1.isSelected() && !g2.isSelected() && g3.isSelected()){
            gl.setText("V");
        }
        if(!g1.isSelected() && !g3.isSelected() && g2.isSelected()){
            gl.setText("E");
        }
        if(!g3.isSelected() && !g2.isSelected() && !g1.isSelected()){
            gl.setText("_____");
        }
        
        }
        else{
            g2.setSelected(false);
            g3.setSelected(false);
            gl.setText("L");
        }
    }//GEN-LAST:event_g1ActionPerformed

    private void h1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h1ActionPerformed
        // TODO add your handling code here:
        if(dobles.isSelected()){
         if(h1.isSelected()&& h2.isSelected()){
             hl.setText("LE");
         }
         if (h1.isSelected()&& h3.isSelected()){
             hl.setText("LV");
         }
         if(h2.isSelected() && h3.isSelected()){
             hl.setText("EV");
         }
         if (h2.isSelected() && h3.isSelected()&& h1.isSelected()){
             hl.setText("LEV");
         }
        if(!h3.isSelected() && !h2.isSelected() && h1.isSelected()){
            hl.setText("L");
        }
        if(!h1.isSelected() && !h2.isSelected() && h3.isSelected()){
            hl.setText("V");
        }
        if(!h1.isSelected() && !h3.isSelected() && h2.isSelected()){
            hl.setText("E");
        }
        if(!h3.isSelected() && !h2.isSelected() && !h1.isSelected()){
            hl.setText("_____");
        }
        
        }
        else{
        h2.setSelected(false);
            h3.setSelected(false);
            hl.setText("L");
        }
    }//GEN-LAST:event_h1ActionPerformed

    private void e1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e1ActionPerformed
        // TODO add your handling code here:
         if(dobles.isSelected()){
         if(e1.isSelected()&& e2.isSelected()){
             el.setText("LE");
         }
         if (e1.isSelected()&& e3.isSelected()){
             el.setText("LV");
         }
         if(e2.isSelected() && e3.isSelected()){
             el.setText("EV");
         }
         if (e2.isSelected() && e3.isSelected()&& e1.isSelected()){
             el.setText("LEV");
         }
        if(!e3.isSelected() && !e2.isSelected() && e1.isSelected()){
            el.setText("L");
        }
        if(!e1.isSelected() && !e2.isSelected() && e3.isSelected()){
            el.setText("V");
        }
        if(!e1.isSelected() && !e3.isSelected() && e2.isSelected()){
            el.setText("E");
        }
        if(!e3.isSelected() && !e2.isSelected() && !e1.isSelected()){
            el.setText("_____");
        }
        
        }
        else{
            e2.setSelected(false);
            e3.setSelected(false);
            el.setText("L");
        }
    }//GEN-LAST:event_e1ActionPerformed

    private void f1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f1ActionPerformed
        // TODO add your handling code here:
        if(dobles.isSelected()){
         if(f1.isSelected()&& f2.isSelected()){
             fl.setText("LE");
         }
         if (f1.isSelected()&& f3.isSelected()){
             fl.setText("LV");
         }
         if(f2.isSelected() && f3.isSelected()){
             fl.setText("EV");
         }
         if (f2.isSelected() && f3.isSelected()&& f1.isSelected()){
             fl.setText("LEV");
         }
        if(!f3.isSelected() && !f2.isSelected() && f1.isSelected()){
            fl.setText("L");
        }
        if(!f1.isSelected() && !f2.isSelected() && f3.isSelected()){
            fl.setText("V");
        }
        if(!f1.isSelected() && !f3.isSelected() && f2.isSelected()){
            fl.setText("E");
        }
        if(!f3.isSelected() && !f2.isSelected() && !f1.isSelected()){
            fl.setText("_____");
        }
        
        }
        else{
            f2.setSelected(false);
            f3.setSelected(false);
            fl.setText("L");
        }
    }//GEN-LAST:event_f1ActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
        // TODO add your handling code here:
        if(dobles.isSelected()){
         if(a1.isSelected()&& a2.isSelected()){
             al.setText("LE");
             
         }
         if (a2.isSelected()&& a3.isSelected()){
             al.setText("EV");
             
         }
         if(a1.isSelected() && a3.isSelected()){
             al.setText("LV");
             
         }
         if (a2.isSelected() && a3.isSelected()&&a1.isSelected()){
             al.setText("LEV");
             
         }
        if(!a3.isSelected() && !a2.isSelected() && a1.isSelected()){
            al.setText("L");
            
        }
        if(!a1.isSelected() && !a2.isSelected() && a3.isSelected()){
            al.setText("V");
            
        }
        if(!a1.isSelected() && !a3.isSelected() && a2.isSelected()){
            al.setText("E");
            
        }
        if(!a3.isSelected() && !a2.isSelected() && !a1.isSelected()){
            al.setText("_____");
            
        }
        
        }
        else{
        a1.setSelected(false);
            a3.setSelected(false);
            al.setText("E");
    }
    }//GEN-LAST:event_a2ActionPerformed

    private void a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3ActionPerformed
        // TODO add your handling code here:
        if(dobles.isSelected()){
         if(a3.isSelected()&& a2.isSelected()){
             al.setText("EV");
             
         }
         if (a1.isSelected()&& a3.isSelected()){
             al.setText("LV");
             
         }
         if(a2.isSelected() && a1.isSelected()){
             al.setText("LE");
             
         }
         if (a2.isSelected() && a3.isSelected()&&a1.isSelected()){
             al.setText("LEV");
             
         }
        if(!a3.isSelected() && !a2.isSelected() && a1.isSelected()){
            al.setText("L");
            
        }
        if(!a1.isSelected() && !a2.isSelected() && a3.isSelected()){
            al.setText("V");
            
        }
        if(!a1.isSelected() && !a3.isSelected() && a2.isSelected()){
            al.setText("E");
            
        }
        if(!a3.isSelected() && !a2.isSelected() && !a1.isSelected()){
            al.setText("_____");
            
        }
        }
        else{
            a2.setSelected(false);
            a1.setSelected(false);
            al.setText("V");
        }
    }//GEN-LAST:event_a3ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        if(dobles.isSelected()){
         if(b1.isSelected()&& b2.isSelected()){
             bl.setText("LE");
         }
         if (b1.isSelected()&& b3.isSelected()){
             bl.setText("LV");
         }
         if(b2.isSelected() && b3.isSelected()){
             bl.setText("EV");
         }
         if (b2.isSelected() && b3.isSelected()&&b1.isSelected()){
             bl.setText("LEV");
         }
        if(!b3.isSelected() && !b2.isSelected() && b1.isSelected()){
            bl.setText("L");
        }
        if(!b1.isSelected() && !b2.isSelected() && b3.isSelected()){
            bl.setText("V");
        }
        if(!b1.isSelected() && !b3.isSelected() && b2.isSelected()){
            bl.setText("E");
        }
        if(!b3.isSelected() && !b2.isSelected() && !b1.isSelected()){
            bl.setText("_____");
        }
        
        }
        else{
            b1.setSelected(false);
            b3.setSelected(false);
            bl.setText("E");
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        if(dobles.isSelected()){
         if(b1.isSelected()&& b2.isSelected()){
             bl.setText("LE");
         }
         if (b1.isSelected()&& b3.isSelected()){
             bl.setText("LV");
         }
         if(b2.isSelected() && b3.isSelected()){
             bl.setText("EV");
         }
         if (b2.isSelected() && b3.isSelected()&&b1.isSelected()){
             bl.setText("LEV");
         }
        if(!b3.isSelected() && !b2.isSelected() && b1.isSelected()){
            bl.setText("L");
        }
        if(!b1.isSelected() && !b2.isSelected() && b3.isSelected()){
            bl.setText("V");
        }
        if(!b1.isSelected() && !b3.isSelected() && b2.isSelected()){
            bl.setText("E");
        }
        if(!b3.isSelected() && !b2.isSelected() && !b1.isSelected()){
            bl.setText("_____");
        }
        
        }
        else{
            b2.setSelected(false);
            b1.setSelected(false);
            bl.setText("V");
            
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        if(dobles.isSelected()){
         if(c1.isSelected()&& c2.isSelected()){
             cl.setText("LE");
         }
         if (c1.isSelected()&& c3.isSelected()){
             cl.setText("LV");
         }
         if(c2.isSelected() && c3.isSelected()){
             cl.setText("EV");
         }
         if (c2.isSelected() && c3.isSelected()&& c1.isSelected()){
             cl.setText("LEV");
         }
        if(!c3.isSelected() && !c2.isSelected() && c1.isSelected()){
            cl.setText("L");
        }
        if(!c1.isSelected() && !c2.isSelected() && c3.isSelected()){
            cl.setText("V");
        }
        if(!c1.isSelected() && !c3.isSelected() && c2.isSelected()){
            cl.setText("E");
        }
        if(!c3.isSelected() && !c2.isSelected() && !c1.isSelected()){
            cl.setText("_____");
        }
        
        }
        else{
            c1.setSelected(false);
            c3.setSelected(false);
            cl.setText("E");
        }
    }//GEN-LAST:event_c2ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        if(dobles.isSelected()){
         if(c1.isSelected()&& c2.isSelected()){
             cl.setText("LE");
         }
         if (c1.isSelected()&& c3.isSelected()){
             cl.setText("LV");
         }
         if(c2.isSelected() && c3.isSelected()){
             cl.setText("EV");
         }
         if (c2.isSelected() && c3.isSelected()&& c1.isSelected()){
             cl.setText("LEV");
         }
        if(!c3.isSelected() && !c2.isSelected() && c1.isSelected()){
            cl.setText("L");
        }
        if(!c1.isSelected() && !c2.isSelected() && c3.isSelected()){
            cl.setText("V");
        }
        if(!c1.isSelected() && !c3.isSelected() && c2.isSelected()){
            cl.setText("E");
        }
        if(!c3.isSelected() && !c2.isSelected() && !c1.isSelected()){
            cl.setText("_____");
        }
        
        }
        else{
            c2.setSelected(false);
            c1.setSelected(false);
            cl.setText("V");
        }
    }//GEN-LAST:event_c3ActionPerformed

    private void d2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d2ActionPerformed
        // TODO add your handling code here:
         if(dobles.isSelected()){
         if(d1.isSelected()&& d2.isSelected()){
             dl.setText("LE");
         }
         if (d1.isSelected()&& d3.isSelected()){
             dl.setText("LV");
         }
         if(d2.isSelected() && d3.isSelected()){
             dl.setText("EV");
         }
         if (d2.isSelected() && d3.isSelected()&& d1.isSelected()){
             dl.setText("LEV");
         }
        if(!d3.isSelected() && !d2.isSelected() && d1.isSelected()){
            dl.setText("L");
        }
        if(!d1.isSelected() && !d2.isSelected() && d3.isSelected()){
            dl.setText("V");
        }
        if(!d1.isSelected() && !d3.isSelected() && d2.isSelected()){
            dl.setText("E");
        }
        if(!d3.isSelected() && !d2.isSelected() && !d1.isSelected()){
            dl.setText("_____");
        }
        
        }
        else{
            d1.setSelected(false);
            d3.setSelected(false);
            dl.setText("E");
        }
    }//GEN-LAST:event_d2ActionPerformed

    private void d3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d3ActionPerformed
        // TODO add your handling code here:
         if(dobles.isSelected()){
         if(d1.isSelected()&& d2.isSelected()){
             dl.setText("LE");
         }
         if (d1.isSelected()&& d3.isSelected()){
             dl.setText("LV");
         }
         if(d2.isSelected() && d3.isSelected()){
             dl.setText("EV");
         }
         if (d2.isSelected() && d3.isSelected()&& d1.isSelected()){
             dl.setText("LEV");
         }
        if(!d3.isSelected() && !d2.isSelected() && d1.isSelected()){
            dl.setText("L");
        }
        if(!d1.isSelected() && !d2.isSelected() && d3.isSelected()){
            dl.setText("V");
        }
        if(!d1.isSelected() && !d3.isSelected() && d2.isSelected()){
            dl.setText("E");
        }
        if(!d3.isSelected() && !d2.isSelected() && !d1.isSelected()){
            dl.setText("_____");
        }
        
        }
        else{
            d2.setSelected(false);
            d1.setSelected(false);
            dl.setText("V");
        }
    }//GEN-LAST:event_d3ActionPerformed

    private void e2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e2ActionPerformed
        // TODO add your handling code here:
        if(dobles.isSelected()){
         if(e1.isSelected()&& e2.isSelected()){
             el.setText("LE");
         }
         if (e1.isSelected()&& e3.isSelected()){
             el.setText("LV");
         }
         if(e2.isSelected() && e3.isSelected()){
             el.setText("EV");
         }
         if (e2.isSelected() && e3.isSelected()&& e1.isSelected()){
             el.setText("LEV");
         }
        if(!e3.isSelected() && !e2.isSelected() && e1.isSelected()){
            el.setText("L");
        }
        if(!e1.isSelected() && !e2.isSelected() && e3.isSelected()){
            el.setText("V");
        }
        if(!e1.isSelected() && !e3.isSelected() && e2.isSelected()){
            el.setText("E");
        }
        if(!e3.isSelected() && !e2.isSelected() && !e1.isSelected()){
            el.setText("_____");
        }
        
        }
        else{
            e1.setSelected(false);
            e3.setSelected(false);
            el.setText("E");
        }
    }//GEN-LAST:event_e2ActionPerformed

    private void e3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e3ActionPerformed
        // TODO add your handling code here:
        if(dobles.isSelected()){
         if(e1.isSelected()&& e2.isSelected()){
             el.setText("LE");
         }
         if (e1.isSelected()&& e3.isSelected()){
             el.setText("LV");
         }
         if(e2.isSelected() && e3.isSelected()){
             el.setText("EV");
         }
         if (e2.isSelected() && e3.isSelected()&& e1.isSelected()){
             el.setText("LEV");
         }
        if(!e3.isSelected() && !e2.isSelected() && e1.isSelected()){
            el.setText("L");
        }
        if(!e1.isSelected() && !e2.isSelected() && e3.isSelected()){
            el.setText("V");
        }
        if(!e1.isSelected() && !e3.isSelected() && e2.isSelected()){
            el.setText("E");
        }
        if(!e3.isSelected() && !e2.isSelected() && !e1.isSelected()){
            el.setText("_____");
        }
        
        }
        else{
            e2.setSelected(false);
            e1.setSelected(false);
            el.setText("V");
        }
    }//GEN-LAST:event_e3ActionPerformed

    private void f2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f2ActionPerformed
        // TODO add your handling code here:
         if(dobles.isSelected()){
         if(f1.isSelected()&& f2.isSelected()){
             fl.setText("LE");
         }
         if (f1.isSelected()&& f3.isSelected()){
             fl.setText("LV");
         }
         if(f2.isSelected() && f3.isSelected()){
             fl.setText("EV");
         }
         if (f2.isSelected() && f3.isSelected()&& f1.isSelected()){
             fl.setText("LEV");
         }
        if(!f3.isSelected() && !f2.isSelected() && f1.isSelected()){
            fl.setText("L");
        }
        if(!f1.isSelected() && !f2.isSelected() && f3.isSelected()){
            fl.setText("V");
        }
        if(!f1.isSelected() && !f3.isSelected() && f2.isSelected()){
            fl.setText("E");
        }
        if(!f3.isSelected() && !f2.isSelected() && !f1.isSelected()){
            fl.setText("_____");
        }
        
        }
        else{
            f1.setSelected(false);
            f3.setSelected(false);
            fl.setText("E");
        }
    }//GEN-LAST:event_f2ActionPerformed

    private void f3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f3ActionPerformed
        // TODO add your handling code here:
         if(dobles.isSelected()){
         if(f1.isSelected()&& f2.isSelected()){
             fl.setText("LE");
         }
         if (f1.isSelected()&& f3.isSelected()){
             fl.setText("LV");
         }
         if(f2.isSelected() && f3.isSelected()){
             fl.setText("EV");
         }
         if (f2.isSelected() && f3.isSelected()&& f1.isSelected()){
             fl.setText("LEV");
         }
        if(!f3.isSelected() && !f2.isSelected() && f1.isSelected()){
            fl.setText("L");
        }
        if(!f1.isSelected() && !f2.isSelected() && f3.isSelected()){
            fl.setText("V");
        }
        if(!f1.isSelected() && !f3.isSelected() && f2.isSelected()){
            fl.setText("E");
        }
        if(!f3.isSelected() && !f2.isSelected() && !f1.isSelected()){
            fl.setText("_____");
        }
        
        }
        else{
            f2.setSelected(false);
            f1.setSelected(false);
            fl.setText("V");
        }
    }//GEN-LAST:event_f3ActionPerformed

    private void g2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g2ActionPerformed
        // TODO add your handling code here:
        if(dobles.isSelected()){
         if(g1.isSelected()&& g2.isSelected()){
             gl.setText("LE");
         }
         if (g1.isSelected()&& g3.isSelected()){
             gl.setText("LV");
         }
         if(g2.isSelected() && g3.isSelected()){
             gl.setText("EV");
         }
         if (g2.isSelected() && g3.isSelected()&& g1.isSelected()){
             gl.setText("LEV");
         }
        if(!g3.isSelected() && !g2.isSelected() && g1.isSelected()){
            gl.setText("L");
        }
        if(!g1.isSelected() && !g2.isSelected() && g3.isSelected()){
            gl.setText("V");
        }
        if(!g1.isSelected() && !g3.isSelected() && g2.isSelected()){
            gl.setText("E");
        }
        if(!g3.isSelected() && !g2.isSelected() && !g1.isSelected()){
            gl.setText("_____");
        }
        
        }
        else{
            g1.setSelected(false);
            g3.setSelected(false);
            gl.setText("E");
        }
    }//GEN-LAST:event_g2ActionPerformed

    private void g3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g3ActionPerformed
        // TODO add your handling code here:
        if(dobles.isSelected()){
         if(g1.isSelected()&& g2.isSelected()){
             gl.setText("LE");
         }
         if (g1.isSelected()&& g3.isSelected()){
             gl.setText("LV");
         }
         if(g2.isSelected() && g3.isSelected()){
             gl.setText("EV");
         }
         if (g2.isSelected() && g3.isSelected()&& g1.isSelected()){
             gl.setText("LEV");
         }
        if(!g3.isSelected() && !g2.isSelected() && g1.isSelected()){
            gl.setText("L");
        }
        if(!g1.isSelected() && !g2.isSelected() && g3.isSelected()){
            gl.setText("V");
        }
        if(!g1.isSelected() && !g3.isSelected() && g2.isSelected()){
            gl.setText("E");
        }
        if(!g3.isSelected() && !g2.isSelected() && !g1.isSelected()){
            gl.setText("_____");
        }
        
        }
        else{
            g2.setSelected(false);
            g1.setSelected(false);
            gl.setText("V");
        }
    }//GEN-LAST:event_g3ActionPerformed

    private void h2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h2ActionPerformed
        // TODO add your handling code here:
        if(dobles.isSelected()){
         if(h1.isSelected()&& h2.isSelected()){
             hl.setText("LE");
         }
         if (h1.isSelected()&& h3.isSelected()){
             hl.setText("LV");
         }
         if(h2.isSelected() && h3.isSelected()){
             hl.setText("EV");
         }
         if (h2.isSelected() && h3.isSelected()&& h1.isSelected()){
             hl.setText("LEV");
         }
        if(!h3.isSelected() && !h2.isSelected() && h1.isSelected()){
            hl.setText("L");
        }
        if(!h1.isSelected() && !h2.isSelected() && h3.isSelected()){
            hl.setText("V");
        }
        if(!h1.isSelected() && !h3.isSelected() && h2.isSelected()){
            hl.setText("E");
        }
        if(!h3.isSelected() && !h2.isSelected() && !h1.isSelected()){
            hl.setText("_____");
        }
        
        }
        else{
            h1.setSelected(false);
            h3.setSelected(false);
            hl.setText("E");
        }
    }//GEN-LAST:event_h2ActionPerformed

    private void h3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h3ActionPerformed
        // TODO add your handling code here:
        if(dobles.isSelected()){
         if(h1.isSelected()&& h2.isSelected()){
             hl.setText("LE");
         }
         if (h1.isSelected()&& h3.isSelected()){
             hl.setText("LV");
         }
         if(h2.isSelected() && h3.isSelected()){
             hl.setText("EV");
         }
         if (h2.isSelected() && h3.isSelected()&& h1.isSelected()){
             hl.setText("LEV");
         }
        if(!h3.isSelected() && !h2.isSelected() && h1.isSelected()){
            hl.setText("L");
        }
        if(!h1.isSelected() && !h2.isSelected() && h3.isSelected()){
            hl.setText("V");
        }
        if(!h1.isSelected() && !h3.isSelected() && h2.isSelected()){
            hl.setText("E");
        }
        if(!h3.isSelected() && !h2.isSelected() && !h1.isSelected()){
            hl.setText("_____");
        }
        
        }
        else{
            h2.setSelected(false);
            h1.setSelected(false);
            hl.setText("V");
        }
    }//GEN-LAST:event_h3ActionPerformed

    private void doblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doblesActionPerformed
        // TODO add your handling code here:
        if ((a1.isSelected() || a2.isSelected() || a3.isSelected())&& ((b1.isSelected() || b2.isSelected() || b3.isSelected())) && ((c1.isSelected() || c2.isSelected() || c3.isSelected())) && ((d1.isSelected() || d2.isSelected() || d3.isSelected())) && ((e1.isSelected() || e2.isSelected() || e3.isSelected())) && ((f1.isSelected() || f2.isSelected() || f3.isSelected())) && ((g1.isSelected() || g2.isSelected() || g3.isSelected())) && ((h1.isSelected() || h2.isSelected() || h3.isSelected()))){
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Favor de llenar completamente la quiniela");
            dobles.setSelected(false);
        }
                
    }//GEN-LAST:event_doblesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        contdoble=0;
        contadortriple=0;
        double tot=0,res=0;
        a=1;
        b=1;
        c=1;
        d=1;
        e=1;
        f=1;
        g=1;
        h=1;
        
        if(dobles.isSelected())
        {
            if(a1.isSelected() && a2.isSelected() && !a3.isSelected())
            {
                a++;
            }
            if(a1.isSelected() && a3.isSelected() && !a2.isSelected())
            {
                a++;
            }
            if(a3.isSelected() && a2.isSelected() && !a1.isSelected())
            {
                a++;
            }
            if(a1.isSelected() && a2.isSelected() && a3.isSelected())
            {
                a+=2;
            }
            
            if(b1.isSelected() && b2.isSelected() && !b3.isSelected())
            {
                b++;
            }
            if(b1.isSelected() && b3.isSelected() && !b2.isSelected())
            {
                b++;
            }
            if(b3.isSelected() && b2.isSelected() && !b1.isSelected())
            {
                b++;
            }
            if(b1.isSelected() && b2.isSelected() && b3.isSelected())
            {
                b+=2;
            }
            
            if(c1.isSelected() && c2.isSelected() && !c3.isSelected())
            {
                c++;
            }
            if(c1.isSelected() && c3.isSelected() && !c2.isSelected())
            {
                c++;
            }
            if(c3.isSelected() && c2.isSelected() && !c1.isSelected())
            {
                c++;
            }
            if(c1.isSelected() && c2.isSelected() && c3.isSelected())
            {
                c+=2;
            }
            
            if(d1.isSelected() && d2.isSelected() && !d3.isSelected())
            {
                d++;
            }
            if(d1.isSelected() && d3.isSelected() && !d2.isSelected())
            {
                d++;
            }
            if(d3.isSelected() && d2.isSelected() && !d1.isSelected())
            {
                d++;
            }
            if(d1.isSelected() && d2.isSelected() && d3.isSelected())
            {
                d+=2;
            }
            
            if(e1.isSelected() && e2.isSelected() && !e3.isSelected())
            {
                e++;
            }
            if(e1.isSelected() && e3.isSelected() && !e2.isSelected())
            {
                e++;
            }
            if(e3.isSelected() && e2.isSelected() && !e1.isSelected())
            {
                e++;
            }
            if(e1.isSelected() && e2.isSelected() && e3.isSelected())
            {
                e+=2;
            }
            
            if(f1.isSelected() && f2.isSelected() && !f3.isSelected())
            {
                f++;
            }
            if(f1.isSelected() && f3.isSelected() && !f2.isSelected())
            {
                f++;
            }
            if(f3.isSelected() && f2.isSelected() && !f1.isSelected())
            {
                f++;
            }
            if(f1.isSelected() && f2.isSelected() && f3.isSelected())
            {
                f+=2;
            }
            
            if(g1.isSelected() && g2.isSelected() && !g3.isSelected())
            {
                g++;
            }
            if(g1.isSelected() && g3.isSelected() && !g2.isSelected())
            {
                g++;
            }
            if(g3.isSelected() && g2.isSelected() && !g1.isSelected())
            {
                g++;
            }
            if(g1.isSelected() && g2.isSelected() && g3.isSelected())
            {
                g+=2;
            }
            
            if(h1.isSelected() && h2.isSelected() && !h3.isSelected())
            {
                h++;
            }
            if(h1.isSelected() && h3.isSelected() && !h2.isSelected())
            {
                h++;
            }
            if(h3.isSelected() && h2.isSelected() && !h1.isSelected())
            {
                h++;
            }
            if(h1.isSelected() && h2.isSelected() && h3.isSelected())
            {
                h+=2;
            }
                        
            
           if(a==2){
               contdoble++;
           }else if(a==3){
               contadortriple++;
           }
           if(b==2){
               contdoble++;
           }else if(b==3){
               contadortriple++;
           }
           if(c==2){
               contdoble++;
           }else if(c==3){
               contadortriple++;
           }
           if(d==2){
               contdoble++;
           }else if(d==3){
               contadortriple++;
           }
           if(e==2){
               contdoble++;
           }else if(e==3){
               contadortriple++;
           }
           if(f==2){
               contdoble++;
           }else if(f==3){
               contadortriple++;
           }
           if(g==2){
               contdoble++;
           }else if(g==3){
               contadortriple++;
           }
           if(h==2){
               contdoble++;
           }else if(h==3){
               contadortriple++;
           }
           
            tot= (Math.pow(2,contdoble) * (Math.pow(3,contadortriple)));
            res=tot*25;
            numq.setText(String.valueOf(tot));
            costo.setText(String.valueOf(res));
        }
        else{
             tot=1; 
       res= 25;
       numq.setText(String.valueOf(tot));
       
       costo.setText(String.valueOf(res));
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton a1;
    private javax.swing.JRadioButton a2;
    private javax.swing.JRadioButton a3;
    private javax.swing.JLabel al;
    private javax.swing.JRadioButton b1;
    private javax.swing.JRadioButton b2;
    private javax.swing.JRadioButton b3;
    private javax.swing.JLabel bl;
    private javax.swing.JRadioButton c1;
    private javax.swing.JRadioButton c2;
    private javax.swing.JRadioButton c3;
    private javax.swing.JLabel cl;
    private javax.swing.JLabel costo;
    private javax.swing.JRadioButton d1;
    private javax.swing.JRadioButton d2;
    private javax.swing.JRadioButton d3;
    private javax.swing.JLabel dl;
    private javax.swing.JCheckBox dobles;
    private javax.swing.JRadioButton e1;
    private javax.swing.JRadioButton e2;
    private javax.swing.JRadioButton e3;
    private javax.swing.JLabel el;
    private javax.swing.JRadioButton f1;
    private javax.swing.JRadioButton f2;
    private javax.swing.JRadioButton f3;
    private javax.swing.JLabel fl;
    private javax.swing.JRadioButton g1;
    private javax.swing.JRadioButton g2;
    private javax.swing.JRadioButton g3;
    private javax.swing.JLabel gl;
    private javax.swing.JRadioButton h1;
    private javax.swing.JRadioButton h2;
    private javax.swing.JRadioButton h3;
    private javax.swing.JLabel hl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel numq;
    // End of variables declaration//GEN-END:variables
}
